apiVersion: apps/v1
kind: Deployment
metadata:
  name: do-visit-counter-backend2
  labels:
    name: do-visit-counter-backend2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: do-visit-counter-backend2
  template:
    metadata:
      labels:
        app: do-visit-counter-backend2
    spec:
      containers:
        - name: do-visit-counter-backend2
          image: mikala3/do-visit-counter-backend2:v1
          imagePullPolicy: Always
          ports:
            - name: backend-port
              containerPort: 5100
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
    name: do-visit-counter-backend2
spec:
    selector:
        app: do-visit-counter-backend2
    ports:
        - port: 5100
          targetPort: 5100
          name: http
